CREATE DATABASE BOARD DEFAULT CHARACTER SET UTF8;

GRANT ALL PRIVILEGES ON *.* TO 'jspexam'@'localhost';

GRANT ALL PRIVILEGES ON *.* TO 'jspexam'@'%';

CREATE TABLE BOARD.MEMBER (
	MEMBER_NO INT AUTO_INCREMENT PRIMARY KEY,
	MEMBER_ID VARCHAR(100),
	MEMBER_PASSWORD VARCHAR(20) NOT NULL,
	MEMBER_NAME VARCHAR(50) NOT NULL,
	MEMBER_PHONE VARCHAR(11) NOT NULL,
	IS_DELETE CHAR(1) DEFAULT 'N',
	INSERTED_DATE DATETIME NOT NULL,
	UPDATED_DATE DATETIME NOT NULL
) ENGINE=INNODB DEFAULT CHARACTER SET = UTF8;

CREATE TABLE BOARD.ARTICLE_CATEGORY (
	CATEGORY_NO INT AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_NAME VARCHAR(255) NOT NULL,
	IS_DELETE CHAR(1) DEFAULT 'N',
	INSERTED_DATE DATETIME NOT NULL,
	UPDATED_DATE DATETIME NOT NULL
) ENGINE=INNODB DEFAULT CHARACTER SET = UTF8;

CREATE TABLE BOARD.ARTICLE (
	ARTICLE_NO INT AUTO_INCREMENT PRIMARY KEY,
	ARTICLE_TITLE VARCHAR(255) NOT NULL,
	ARTICLE_CONTENT TEXT NOT NULL,
	READ_CNT INT DEFAULT 0,
	MEMBER_NO INT NOT NULL,
	CATEGORY_NO INT NOT NULL,
	IS_DELETE CHAR(1) DEFAULT 'N',
	INSERTED_DATE DATETIME NOT NULL,
	UPDATED_DATE DATETIME NOT NULL
) ENGINE=INNODB DEFAULT CHARACTER SET = UTF8;

CREATE TABLE BOARD.FILES (
	FILE_NO INT AUTO_INCREMENT PRIMARY KEY,
	FILE_ORIGINAL_NAME VARCHAR(255) NOT NULL,
	FILE_STORED_NAME VARCHAR(255) NOT NULL,
	FILE_SIZE INT NOT NULL,
	FILE_EXTENSION VARCHAR(20) NOT NULL,
	ARTICLE_NO INT NOT NULL,
	IS_DELETE CHAR(1) DEFAULT 'N',
	INSERTED_DATE DATETIME NOT NULL,
	UPDATED_DATE DATETIME NOT NULL
) ENGINE=INNODB DEFAULT CHARACTER SET = UTF8;

CREATE TABLE BOARD.COMMENT (
	COMMENT_NO INT AUTO_INCREMENT PRIMARY KEY,
	COMMENT_CONTENT VARCHAR(1000) NOT NULL,
	PARENT_COMMENT_NO INT DEFAULT 0,
	COMMENT_ORDER INT DEFAULT 0,
	ARTICLE_NO INT NOT NULL,
	MEMBER_NO INT NOT NULL,
	IS_DELETE CHAR(1) DEFAULT 'N',
	INSERTED_DATE DATETIME NOT NULL,
	UPDATED_DATE DATETIME NOT NULL
) ENGINE=INNODB DEFAULT CHARACTER SET = UTF8;

SELECT * FROM BOARD.MEMBER;

SELECT * FROM BOARD.ARTICLE_CATEGORY;

SELECT * FROM BOARD.ARTICLE;

SELECT * FROM BOARD.FILES;

SELECT * FROM BOARD.COMMENT;